# Generated by Django 3.0 on 2020-10-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to='school.UserType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to='school.UserType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='school.UserType'),
            preserve_default=False,
        ),
    ]
