# Generated by Django 3.0 on 2020-10-10 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0003_auto_20201010_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminHod',
        ),
    ]
