# Generated by Django 3.0 on 2020-10-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20201010_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
    ]
